stages:
  - build
  - release

build:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:latest
  rules:
    - if: '$CI_COMMIT_TAG'
  script:
    - cd desktop/
    - chmod u+x build.sh
    - ./build.sh
release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: '$CI_COMMIT_TAG'
  needs:
    - job: build
      artifacts: true
  script:
    - echo "Creating GitLab release for tag $TAG"
  artifacts:
    paths:
      - desktop/bin/Release/net9.0/win-x64/Orion-${CI_COMMIT_TAG}.zip
  release:
    tag_name: $CI_COMMIT_TAG
    description: CHANGELOG.md
    ref: "$CI_COMMIT_SHA"