stages:
  - build
  - release

variables:
  ZIP_START_NAME: "Orion"

build:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:latest
  rules:
    - if: '$CI_COMMIT_TAG'
  script:
    - apt-get update && apt-get install -y zip
    - cd desktop/
    - chmod u+x build.sh
    - ./build.sh
    - cd bin/Release/net9.0/win-x64/
    - zip -r Orion.zip publish
    - mv "Orion.zip" "Orion-${CI_COMMIT_TAG}.zip"
  artifacts:
    paths:
      - Orion-${CI_COMMIT_TAG}.zip
    expire_in: 1 hour

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: '$CI_COMMIT_TAG'
  needs:
    - job: build
      artifacts: true
  script:
    - echo "Creating GitLab release for tag $TAG"
  release:
    tag_name: $CI_COMMIT_TAG
    description: "$CI_COMMIT_TAG"
    ref: "$CI_COMMIT_SHA"
    assets:
      links:
      - name: "Télécharger l'exécutable Windows"
        url: 'https://git.s2.rpn.ch/ComtesseE1/orion/-/jobs/permalink/latest/downloads:filepath'
        filepath: desktop/bin/Release/net9.0/win-x64/Orion-${CI_COMMIT_TAG}.zip